version: '3.1'

services:
  db:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd!
      - POSTGRES_DB=phoenix
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres_data:
